test-pub:
	go test -count=1 -v -run=TestPublisher_publish ./test/...

test-pub-order:
	go test -count=1 -v -run=TestPublisher_orderPublish ./test/...

test-sub-async:
	go test -count=1 -v -run=TestSubscriber_pullMessageAsync ./test/...

test-sub-sync:
	go test -count=1 -v -run=TestSubscriber_pullMessageSync ./test/...
